name: {name}
services:
    {name}:
        container_name: {hash}
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        restart: always
        networks:
            - traefuck
        expose: # This should be the port your challenge runs on inside the container.
            - "{port}"
        labels: # If you have a second service make sure the service name and port are replaced
            - "traefik.enable=true"
            - "traefik.tcp.routers.${{COMPOSE_PROJECT_NAME}}.rule=HostSNI(`${{COMPOSE_PROJECT_NAME}}.b01le.rs`)"
            - "traefik.tcp.routers.${{COMPOSE_PROJECT_NAME}}.tls=true"
            - "traefik.tcp.routers.${{COMPOSE_PROJECT_NAME}}.entrypoints=ncsecure"
            - "traefik.tcp.routers.${{COMPOSE_PROJECT_NAME}}.service=${{COMPOSE_PROJECT_NAME}}-svc"
            - "traefik.tcp.services.${{COMPOSE_PROJECT_NAME}}-svc.loadbalancer.server.port={port}"
        ports: # please comment this whole ports field out when you are ready to make PR.
            - "1337:{port}"
networks:
  traefuck:
    name: traefuck
    # please uncomment the below line when making a pr
    # external: true     