services:
    {name}:
        container_name: {hash}
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        restart: always # please keep this in
        networks:
            - traefuck
        expose: # This should be the port your challenge runs on inside the container.
            - "{port}"
        labels: # please do not delete these labels, if you have a second service make sure the service name and port are replaced
            - "traefik.enable=true"
            - "traefik.tcp.routers.${{CHALL_HASH}}.rule=HostSNI(`${{CHALL_HASH}}.b01le.rs`)"
            - "traefik.tcp.routers.${{CHALL_HASH}}.tls=true"
            - "traefik.tcp.routers.${{CHALL_HASH}}.entrypoints=ncsecure"
            - "traefik.tcp.routers.${{CHALL_HASH}}.service=${{CHALL_HASH}}-svc"
            - "traefik.tcp.services.${{CHALL_HASH}}-svc.loadbalancer.server.port={port}"
        ports: # please comment this whole ports field out when you are ready to make PR.
            - "1337:{port}"
networks: # Do not delete this
  traefuck:
    name: traefuck
    # please uncomment the below line when making a pr
    # external: true     