name: {name}
services:
    chall:
        container_name: {hash}
{privileged}        build: .
        logging:
            driver: "json-file"
            options:
                max-size: "50k"
                max-file: "3"
        expose:
            - "{port}"
        ports:
            - "1337:{port}"
{build_services}
