name: {name}
services:
    chall:
        container_name: {hash}
        privileged: true # needed for redpwn jail to work
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
            options:
                max-size: "50k"
                max-file: "3"
        restart: always
        expose: # This should be the port your challenge runs on inside the container.
            - "{port}"
        labels: # please do not delete these labels, if you have a second service make sure the service name and port are replaced
            - "traefik.enable=true"
            - "traefik.tcp.routers.${{COMPOSE_PROJECT_NAME}}.rule=HostSNI(`${{COMPOSE_PROJECT_NAME}}.{root_domain}`)"
            - "traefik.tcp.routers.${{COMPOSE_PROJECT_NAME}}.tls=true"
            - "traefik.tcp.routers.${{COMPOSE_PROJECT_NAME}}.entrypoints=ncsecure"
            - "traefik.tcp.routers.${{COMPOSE_PROJECT_NAME}}.service=${{COMPOSE_PROJECT_NAME}}-svc"
            - "traefik.tcp.services.${{COMPOSE_PROJECT_NAME}}-svc.loadbalancer.server.port={port}"
        ports:
            - "1337:{port}"

    build: # build system for your challenge.
        user: "${{USER_ID}}:${{GROUP_ID}}"
        container_name: {hash}_build
        build:
            dockerfile: ./deploy/Dockerfile_build
            context: ../
        logging:
            driver: "json-file"
        volumes:
            - ../build_out:/build_out
    
    libc: # copies libc and linker out of real challenge.
        user: "${{USER_ID}}:${{GROUP_ID}}"
        container_name: {hash}_libc
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        volumes:
            - ../build_out:/build_out
        entrypoint: ["/bin/sh", "-c"]
        command: [
            "cp ${{LIBC_PATH}} /build_out/libc.so.6 && cp ${{LINKER_PATH}} /build_out/ld-linux-x86-64.so.2",
        ]
