name: {name}
services:
    chall:
        container_name: {hash}
        privileged: true # needed for redpwn jail to work
        build:
            context: ../
            dockerfile: ./src/Dockerfile
        logging:
            driver: "json-file"
            options:
                max-size: "50k"
                max-file: "3"
        restart: always
        expose:
            - "{port}"
        ports:
            - "1337:{port}"

    build: # build system for your challenge.
        user: "${{USER_ID}}:${{GROUP_ID}}"
        container_name: {hash}_build
        build:
            context: ../
            dockerfile: ./src/Dockerfile_build
        logging:
            driver: "json-file"
        volumes:
            - ../build_out:/build_out
    
    libc: # copies libc and linker out of real challenge.
        user: "${{USER_ID}}:${{GROUP_ID}}"
        container_name: {hash}_libc
        build:
            context: ../
            dockerfile: ./src/Dockerfile
        logging:
            driver: "json-file"
        volumes:
            - ../build_out:/build_out
        entrypoint: ["/bin/sh", "-c"]
        command: [
            "cp ${{LIBC_PATH}} /build_out/libc.so.6 && cp ${{LINKER_PATH}} /build_out/ld-linux-x86-64.so.2",
        ]
