services:
    {name}:
        container_name: {hash}
        privileged: true # needed for redpwn jail to work
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        restart: always # please keep this in
        networks:
            - traefuck
        expose: # This should be the port your challenge runs on inside the container.
            - "{port}"
        labels: # please do not delete these labels, if you have a second service make sure the service name and port are replaced
            - "traefik.enable=true"
            - "traefik.tcp.routers.{hash}.rule=HostSNI(`{hash}.b01le.rs`)"
            - "traefik.tcp.routers.{hash}.tls=true"
            - "traefik.tcp.routers.{hash}.entrypoints=ncsecure"
            - "traefik.tcp.routers.{hash}.service={hash}-svc"
            - "traefik.tcp.services.{hash}-svc.loadbalancer.server.port={port}"
        ports: # please comment this whole ports field out when you are ready to make PR.
            - "1337:{port}"
    
    {name}_build: # build system for your challenge.
        user: "${{USER_ID}}:${{GROUP_ID}}"
        container_name: {hash}_build
        build:
            dockerfile: ./deploy/Dockerfile_build
            context: ../
        logging:
            driver: "json-file"
        volumes:
            - ../dist:/dist


networks: # Do not delete this
  traefuck:
    name: traefuck
    external: true   