services:
    {name}:
        container_name: {hash}
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        networks: # please keep this in
            - traefuck
        restart: always # please keep this in
        expose: # This should be the port your challenge runs on inside the container.
            - "{port}"
        labels: # please do not delete these labels, if you have a second service make sure the service name and port are replaced
            - "traefik.http.routers.${{CHALL_HASH}}.rule=Host(`${{CHALL_HASH}}.{root_domain}`)"
            - "traefik.http.services.${{CHALL_HASH}}.loadbalancer.server.port={port}" # should match the exposed port
            - "traefik.http.routers.${{CHALL_HASH}}.tls={{}}"
            - "traefik.http.routers.${{CHALL_HASH}}.entrypoints=websecure"
            # Delete this line, edit and uncomment the lines below to configure rate limiting for your service
            # - "traefik.http.middlewares.fluf.ratelimit.average=100"
            # - "traefik.http.routers.${CHALL_HASH}.middlewares=fluf"  
            # - "traefik.http.middlewares.fluf.ratelimit.burst=100"
        ports: # please comment the ports field out when you are done.
            - "1337:{port}"

networks: # Do not delete this
  traefuck:
    name: traefuck
    # please uncomment the below line when making a pr
    # external: true     
     