[project]
name = "ctf-scripts"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "msgspec>=0.21.1",
    "rich>=15.0.0",
    "ruamel-yaml>=0.18.15",
]

[project.scripts]
mkchal = "ctf_scripts.mkchal:main"
make-dist = "ctf_scripts.make_dist:main"

[dependency-groups]
dev = ["pyright>=1.1.405"]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
include = ["src/ctf_scripts"]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"
