name: Upload challenge metadata to rCTF on merge
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
jobs:
  build_and_deploy:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: b01lers/rctf-deploy-action@main
        with:
          rctf-url: '...'
          rctf-token: ${{ secrets.RCTF_TOKEN }}
